# Dependencies
markdown:       kramdown
# markdown:         redcarpet
highlighter:     rouge 

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Heidi's stats blog
name:		  Heidi's stats blog
tagline:          'Some stuff that interests me'
description:      
url:              http://heidiseibold.github.io/
baseurl:          /

author:
  name:           'Heidi Seibold'
  url:            https://twitter.com/HeidiBaya

paginate:         1

# Custom vars
github:
  repo:		  https://github.com/HeidiSeibold/HeidiSeibold.github.io 
  
# Feed
gems:
  - jekyll-feed
  - jekyll-paginate
  
feed:
  path: atom.xml


exclude: [vendor]
