# Dependencies
markdown:       kramdown
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Heidi's stats blog
tagline:          'Some stuff that interests me'
description:      'I have been wanting to do a blog for a long time. Here it is :)'
url:              http://heidiseibold.github.io/
baseurl:          /

author:
  name:           'Heidi Seibold'
  url:            https://twitter.com/HeidiBaya

paginate:         1

# Custom vars
github:
  repo:		  https://github.com/HeidiSeibold/HeidiSeibold.github.io 
  
# Feed
gems:
  - jekyll-feed
