source "https://rubygems.org/"
#gem "jekyll"          #, "~> 1.5.0"
#gem "jekyll-assets"   #, "~> 0.7.6"
#gem "jekyll-scholar"  #, "~> 2.0.0"
#gem "jekyll-pandoc"   #, "~> 0.0.1"
#gem "jekyll-feed"
#gem 'pandoc-ruby'     #, '~> 0.7.5'
#gem 'psych'           #, '~> 2.0.5'
#gem "json"            #, '~>1.8'

#gem "octokit"#, "~> 2.0"   # Github API (octokit plugin)
#gem "twitter"#, "~> 5.8.0" # Twitter API
#gem "nokogiri"            # HTML / XML parser
#gem "feedjira"            # Atom/RSS parser
#gem "chronic"             # Natural language time parser

#gem "git"         # Git gem
#gem "redcarpet"

#gem "paginate"

gem 'github-pages', group: :jekyll_plugins

gem "rake", "~> 10.4.2"


